-- Generated by nwg-displays on 2026-08-26 at 10:08:09. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "3440x1440@120.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1280x1024@60.02",
    position = "2928x1646",
    scale = 1
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@120.0",
    position = "368x1440",
    scale = 1
})
