-- Generated by nwg-displays on 2026-09-22 at 14:53:11. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@120.0",
    position = "0x0",
    scale = 2.0,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1440x360",
    scale = 2,
    vrr = 0
})
