-- Generated by nwg-displays on 2026-10-07 at 12:19:20. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@120.0",
    position = "3501x-704",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "DP-1",
    mode = "3440x1440@120.0",
    position = "3136x-2144",
    scale = 1,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@165.0",
    position = "6061x-704",
    scale = 1,
    vrr = 0
})
