accent = "#e60012"
cursor = "#ffffff"
foreground = "#f5f5f7"
background = "#0f0f10"
selection_foreground = "#ffffff"
selection_background = "#e60012"

color0 = "#0f0f10"
color1 = "#e60012"
color2 = "#1b6e38"
color3 = "#d1a100"
color4 = "#0b6a99"
color5 = "#702a8c"
color6 = "#008299"
color7 = "#b0b0b5"
color8 = "#48484a"
color9 = "#ff4554"
color10 = "#248a3d"
color11 = "#e6c300"
color12 = "#0090c8"
color13 = "#9a3db5"
color14 = "#00b5d6"
color15 = "#ffffff"
